### PR TITLE
deb: support Debian 11 (bullseye)

### PR DESCRIPTION
**Pull request by kenhys**
Debian 11 "bullseye" released

https://www.debian.org/News/2021/20210814

### CODE REVIEW

**Comment by cosmo0920** [comment]
I confirmed that debian-bullseye amd64 package can be built with this change but built patch is changed in `td-agent/apt/repositories/debian/pool/n/a/main/t/td-agent`.
Note that debian-buster package will be written in `td-agent/apt/repositories/debian/pool/buster/main/t/td-agent`.
Is this change expected?

**Comment by cosmo0920** [comment]
Hmm.., my box docker environment is still pointed at old bullseye image. I re-pulled debian:bullseye image...and testing for this PR.

**Review by cosmo0920 — CHANGES_REQUESTED** [review]
We should add td-agent-apt-source as well:
https://github.com/fluent-plugins-nursery/fluent-package-builder/tree/master/td-agent-apt-source/apt

**Comment by kenhys** [comment]
I've added apt-source too.

**Review by cosmo0920 — APPROVED** [review]
LGTM

**Pull request merged**
